language: python

python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9

install:
  - pip install Cython==0.29.22
  - python setup.py build_ext --inplace

script:
  - python test.py
